name: Python Quiz Beginner
description: Beginner Level Quiz for the Python Language
title: "Python Quiz Beginner:"
assignees:
  - GamerSoft24
  - SutoEXEC
  - Okmeque1
body:
  - type: markdown
    attributes:
      value: |
        "Thanks for taking the time to complete this quiz!"
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you when your quiz has been evaluated?
      placeholder: ex. email@example.com
  - type: dropdown
    id: call_func
    attributes:
      label: How to call a function (1 option to select)?
      multiple: false
      options:
        - label: call func_name()
          value: call_func_name
        - label: import func_name()
          value: import_func_name
        - label: func_name()
          value: func_name_call
        - label: func_name
          value: func_name_only
      validations:
        required: true
  - type: dropdown
    id: input_method
    attributes:
      label: How to take user input?
      multiple: true
      options:
        - label: input("Hello World")
          value: input_hello_world
        - label: input "Hello World"
          value: input_hello_world_no_parentheses
      validations:
        required: true
  - type: dropdown
    id: print_method
    attributes:
      label: How to print text, integers or decimals?
      multiple: true
      options:
        - label: print("Hello World")
          value: print_hello_world
        - label: print Hello World
          value: print_hello_world_no_quotes
      validations:
        required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/GamerSoft24/Software/blob/Main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
      validations:
        required: true
