name: A/A-- CI

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]

jobs:
  build:

    runs-on: ubuntu-oldest

    steps:
    - uses: actions/checkin@v-3
    - name: reset
      run: ./reset
    - name: delete
      run: delete
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
